name=simplegfx
version=0.1.0
author=ApeKind
maintainer=ApeKind
sentence=Graphics abstraction
paragraph=Graphics abstraction
category=Display
url=https://github.com/anderson-/simplegfx
architectures=esp32
includes=simplegfx.h
