#include "keymap.h"

keyinfo_t keymap[] = {
  {-1, "UNKNOWN"},
#if defined(__arm__) && defined(__linux__)
  {BTN_GP_UP, "GP_UP"},
  {BTN_GP_DOWN, "GP_DOWN"},
  {BTN_GP_LEFT, "GP_LEFT"},
  {BTN_GP_RIGHT, "GP_RIGHT"},
  {BTN_GP_A, "GP_A"},
  {BTN_GP_B, "GP_B"},
  {BTN_GP_X, "GP_X"},
  {BTN_GP_Y, "GP_Y"},
  {BTN_GP_L1, "GP_L1"},
  {BTN_GP_R1, "GP_R1"},
  {BTN_GP_L2, "GP_L2"},
  {BTN_GP_R2, "GP_R2"},
  {BTN_GP_SELECT, "GP_SELECT"},
  {BTN_GP_START, "GP_START"},
  {BTN_GP_MENU, "GP_MENU"},
  {BTN_GP_VOL_UP, "GP_VOL_UP"},
  {BTN_GP_VOL_DOWN, "GP_VOL_DOWN"},
  {BTN_GP_POWER_ESC, "GP_POWER_ESC"},
#endif
  {BTN_KB_ESCAPE, "KB_ESCAPE"},
  {BTN_KB_ENTER, "KB_ENTER"},
  {BTN_KB_BACKSPACE, "KB_BACKSPACE"},
  {BTN_KB_DELETE, "KB_DELETE"},
  {BTN_KB_TAB, "KB_TAB"},
  {BTN_KB_SHIFT, "KB_SHIFT"},
  {BTN_KB_CTRL, "KB_CTRL"},
  {BTN_KB_ALT, "KB_ALT"},
  {BTN_KB_ALT2, "KB_ALT2"},
  {BTN_KB_FN, "KB_FN"},
  {BTN_KB_META, "KB_META"},
  {BTN_KB_CAPS_LOCK, "KB_CAPS_LOCK"},
  {BTN_KB_PG_UP, "KB_PG_UP"},
  {BTN_KB_PG_DOWN, "KB_PG_DOWN"},
  {BTN_KB_HOME, "KB_HOME"},
  {BTN_KB_END, "KB_END"},
  {BTN_KB_INSERT, "KB_INSERT"},
  {BTN_KB_UP, "KB_UP"},
  {BTN_KB_DOWN, "KB_DOWN"},
  {BTN_KB_LEFT, "KB_LEFT"},
  {BTN_KB_RIGHT, "KB_RIGHT"},
  {BTN_KB_SPACE, "KB_SPACE"},
#if !(defined(__arm__) && defined(__linux__))
  {BTN_GP_UP, "GP_UP"},
  {BTN_GP_DOWN, "GP_DOWN"},
  {BTN_GP_LEFT, "GP_LEFT"},
  {BTN_GP_RIGHT, "GP_RIGHT"},
  {BTN_GP_A, "GP_A"},
  {BTN_GP_B, "GP_B"},
  {BTN_GP_X, "GP_X"},
  {BTN_GP_Y, "GP_Y"},
  {BTN_GP_L1, "GP_L1"},
  {BTN_GP_R1, "GP_R1"},
  {BTN_GP_L2, "GP_L2"},
  {BTN_GP_R2, "GP_R2"},
  {BTN_GP_SELECT, "GP_SELECT"},
  {BTN_GP_START, "GP_START"},
  {BTN_GP_MENU, "GP_MENU"},
  {BTN_GP_VOL_UP, "GP_VOL_UP"},
  {BTN_GP_VOL_DOWN, "GP_VOL_DOWN"},
  {BTN_GP_POWER_ESC, "GP_POWER_ESC"},
#endif
  {0, 0},
};