#include "keymap.h"

keyinfo_t keymap[] = {
  {-1, "UNKNOWN"},
  {BTN_UP, "UP"},
  {BTN_DOWN, "DOWN"},
  {BTN_LEFT, "LEFT"},
  {BTN_RIGHT, "RIGHT"},
  {BTN_A, "A"},
  {BTN_B, "B"},
  {BTN_X, "X"},
  {BTN_Y, "Y"},
  {BTN_L1, "L1"},
  {BTN_R1, "R1"},
  {BTN_L2, "L2"},
  {BTN_R2, "R2"},
  {BTN_SELECT, "SELECT"},
  {BTN_START, "START"},
  {BTN_MENU, "MENU"},
  {BTN_VOLUME_UP, "VOLUME_UP"},
  {BTN_VOLUME_DOWN, "VOLUME_DOWN"},
  {BTN_POWER, "POWER"},
  {BTN_EXIT, "EXIT"},
  {0, 0},
};